### ISSUE TITLE
Step Two

### ISSUE THREAD

**Issue by domzerchi** [domzerchi/csci-1082-final#1]
The Ninya: Step two is to create a repository that includes a description of our project and get approval from instructor. I think we’ve done that but he will want to see this repository and there is a dropbox on D2L. I uploaded a pdf saying where our project is located, https://github.com/domzerchi/csci-1082-final

Maybe you want to do something similar, just to make sure you get credit.

**Comment by The-Ninya** [comment]
It has been done. (￣^￣)ゞ
