### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by domzerchi** [domzerchi/csci-1082-final#12]
I will figure out the file stuff this (Saturday) afternoon, unless you have already started working on that and you want me to start working on something else.

Go ahead and commit anything you have done, or open an issue at least, so we know what each other are working on and don’t duplicate efforts.

Have you done anything in re images?

**Comment by The-Ninya** [comment]
I have done neither of those things! I'm still working on the Item GUI and the search page's functionality T-T I'll upload what I have.

**Comment by domzerchi** [comment]
Try out the FileChooserDemo.

**Comment by The-Ninya** [comment]
The FileChooserDemo has a nice UI, but it doesn't actually save or open anything. Could I trust you to work on that?
I'll continue working on the action listeners, unless you want to swap or something.

**Comment by domzerchi** [comment]
I’m working on it! :-)

Steve Polson
