### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by domzerchi** [domzerchi/csci-1082-final#6]
Write code for classes: item, collection, tag, search, etc...from UML diagrams

**Comment by domzerchi** [comment]
Should Tag be a class? I think so.

**Comment by domzerchi** [comment]
Added a Tag class. It may need work, in particular input validation in setValue method

**Comment by The-Ninya** [comment]
I think tags should allow whitespace, but what should the character limit be?

**Comment by domzerchi** [comment]
> I think tags should allow whitespace, but what should the character limit be?

I dunno. Maybe not. I think they need to fit well in our GUI.

**Comment by domzerchi** [comment]
> Added a Tag class. It may need work, in particular input validation in setValue method

I fixed Tag so it works, plus driver. I just forced my changes on to the repository. I am not using github correctly yet.
